# Welcome to fangguizhen's blog!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 方贵震的个人专栏
email: fangguizhen@icarephone.com
description: >- # this means to ignore newlines until "baseurl:"
  天下武功，唯快不破.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fangguizhen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: fangguizhen
github_username:  fangguizhen

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 95957166e081b27d74ad                            #生成的clientID
  clientSecret: 87f01e8e6001e14e38d14e6b4cba7bd4da38f480    #生成的clientSecret
  repo: https://fangguizhen.github.io    #仓库名称
  owner: fangguizhen    #github用户名
  admin: fangguizhen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
